version: '3'

services:
  traefik-http-provider-mapper:
    image: beaussan/traefik-http-provider-mapper
    restart: unless-stopped
    environment:
      # Required, the address of the coolify server
      - TRAEFIK_MAPPER_BASE_ENDPOINT=43.204.216.218:3000

      # All the following are optional

      # Replace the web entrypoint with what is provided (eg http here)
      - TRAEFIK_MAPPER_NEW_HTTP_ENTRYPOINT=http
      # Replace the websecure entrypoint with what is provided (eg https here)
      - TRAEFIK_MAPPER_NEW_HTTPS_ENTRYPOINT=https
      # Replace the certificate store (letsencrypt) with what is provided (eg cert here)
      - TRAEFIK_MAPPER_NEW_CERT_RESOLVER=letsencrypt

      # # Adds this middleware to all routes, ex middlewareName@file for a file base middleware, middlewareName@docker for a docker base middleware
      # - TRAEFIK_MAPPER_ADD_MIDDLEWARE_NAME=middlewareName@source

      # # Ignore routers for the middlewares. This can be usefull to filter out some domains
      # - TRAEFIK_MAPPER_IGNORE_MIDDLEWARE_SITES=some.domain.io;some.other.domain.io

      # Remove coolify itself from the list of services
      - TRAEFIK_MAPPER_FILTER_COOLIFY=true
      # Remove www redirect middleware from the list of middlewares
      - TRAEFIK_MAPPER_FILTER_WWW_MIDDLEWARE=true
      # Remove all http routes from the list of routes
      - TRAEFIK_MAPPER_FILTER_HTTP_ROUTERS=true
      # Remove all www routes from the list of routes
      - TRAEFIK_MAPPER_FILTER_WWW_ROUTERS=true

    networks:
      # Hooks itself into the coolify network that your Traefik instance should be running on
      - coolify
    labels:
      # Configure the HTTP Provider Mapper
      - "traefik.http.routers.my-service.rule=Host('test.securih.com')"
      - "traefik.http.routers.my-service.entrypoints=web"
      - "traefik.http.services.my-service.loadbalancer.server.port=80"
      - "traefik.http.services.my-service.loadbalancer.server.port=443"
      - "traefik.http.services.my-service.loadbalancer.sticky=true"
      # Add the Retry middleware with a delay only on 503 Service Unavailable errors
      - "traefik.http.middlewares.my-retry-middleware.retry.initialInterval=100ms"
      - "traefik.http.middlewares.my-retry-middleware.retry.maxInterval=1s"
      - "traefik.http.middlewares.my-retry-middleware.retry.retryOn=502"
      - "traefik.http.middlewares.my-retry-middleware.retry.attempts=1"
      - "traefik.http.middlewares.my-retry-middleware.retry.retryOn=503"
      - "traefik.http.middlewares.my-retry-middleware.retry.retryOn=404"
      - "traefik.http.middlewares.my-retry-middleware.retry.after=10s"
      
networks:
  coolify:
    external: true
  coolify-infra:
    external: true
